#- debug: {{ jar_path }}
- file:
    path=/opt/scripts
    state=directory
- file:
    path=/opt/app/proxy/agent/1.0.0
    state=directory
- file:
    path=/opt/scripts/proxy_env.profile
    state=touch
- lineinfile:
    dest=/opt/scripts/proxy_env.profile
    line="COMPUTERNAME={{ansible_ssh_args}}"
- lineinfile:
    dest=/opt/scripts/proxy_env.profile
    line="IP_ADDRESS={{ansible_ssh_host}}:{{ansible_ssh_port}}"

- name: Delivery jar
  copy: src={{ jar_path }}  dest=/opt/app/proxy/agent/1.0.0/
- name: Cover proxy.service
  template: src=proxy.service dest=/usr/lib/systemd/system/
- name: Restart Proxy
  systemd:
    name: proxy
    daemon_reload: true
    enabled: true
    state: restarted
     
