- name: Stop firewalled
  systemd:
    name: firewalld
    enabled: false
    state: stopped
- name: Install iptables
  yum:
    name: iptables-services
    state: present
- name: 'Add 57112 port for squid'
  lineinfile:
    dest: /etc/sysconfig/iptables
    regexp: 'dport 57112 -j ACCEPT'
    insertafter: 'dport 22 -j ACCEPT'
    line: "-A INPUT -p tcp -m state --state NEW -m tcp --dport 57112 -j ACCEPT"
- name: 'Add 3389 port for WCDMA network'
  lineinfile:
    dest: /etc/sysconfig/iptables
    regexp: 'dport 3389 -j ACCEPT'
    insertafter: 'dport 22 -j ACCEPT'
    line: "-A INPUT -p tcp -m state --state NEW -m tcp --dport 3389 -j ACCEPT"
- name: 'Add 33890 port for mobile network'
  lineinfile:
    dest: /etc/sysconfig/iptables
    regexp: 'dport 33890 -j ACCEPT'
    insertafter: 'dport 22 -j ACCEPT'
    line: "-A INPUT -p tcp -m state --state NEW -m tcp --dport 33890 -j ACCEPT"
- name: Restart iptables
  systemd:
    name: iptables
    daemon_reload: yes
    enabled: yes 
    state: restarted
- sysctl:
    name: net.netfilter.nf_conntrack_max
    value: 655350 
    state: present
- sysctl:
    name: net.netfilter.nf_conntrack_tcp_timeout_established
    value: 1200
    state: present
    reload: yes
